version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx-portainer
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/dan-ubuntu/cloudflare/ssl_cert:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - portainer 

volumes:
  portainer_data:

